            <SmallCard
              name={"New Account Opening"}
              imgSrc={newAcc}
              mobNo={"254512152323"}
              emailId={"sale@huufgjfhj"}
            />

            <SmallCard
              name={"Support"}
              imgSrc={supportImg}
              mobNo={"254512152323"}
            />
            <SmallCard
              name={"Funds Deposit/Withdrawal"}
              imgSrc={contactCardImg}
              mobNo={"254512152323"}
              emailId={"sale@huufgjfhj"}
            />
            <SmallCard
              name={"Admin/RMS"}
              imgSrc={userImg}
              mobNo={"254512152323"}
              emailId={"sale@huufgjfhj"}
            />
            <SmallCard
              name={"Trading/Dealing"}
              imgSrc={chartImg}
              mobNo={"254512152323"}
            />
            <SmallCard
              name={"Partnership"}
              imgSrc={connectingPeopleImg}
              mobNo={"254512152323"}
            />
            <SmallCard
              name={"Modification/Reactivation"}
              imgSrc={gearImg}
              mobNo={"254512152323"}
            />
            <SmallCard
              name={"Department"}
              imgSrc={fileImg}
              mobNo={"254512152323"}
            />